version: '3.8'

services:
  portfolio-nuxt-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NUXT_PUBLIC_TURNSTILE_SITE_KEY=${NUXT_PUBLIC_TURNSTILE_SITE_KEY}
        - NUXT_TURNSTILE_SECRET_KEY=${NUXT_TURNSTILE_SECRET_KEY}
        - NUXT_GHOST_KEY=${NUXT_GHOST_KEY}
        - NUXT_GHOST_URL=${NUXT_GHOST_URL}
    container_name: portfolio-nuxt
    ports:
      - "3000:3000"
    environment:
      - NUXT_BREVO_API_KEY=${NUXT_BREVO_API_KEY}
      - NUXT_TO_EMAIL=${NUXT_TO_EMAIL}
      - NUXT_GHOST_KEY=${NUXT_GHOST_KEY}
      - NUXT_GHOST_URL=${NUXT_GHOST_URL}
      - NUXT_PUBLIC_TURNSTILE_SITE_KEY=${NUXT_PUBLIC_TURNSTILE_SITE_KEY}
      - NUXT_TURNSTILE_SECRET_KEY=${NUXT_TURNSTILE_SECRET_KEY}
    volumes:
      - ./nitro-data:/.data
      - ./data:/app/data
    restart: always